title: CovidSight
description: Covid-19 Tracking Application
theme: jekyll-theme-slate
google_analytics:
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/Covid-Sight/covid-sight
gems:
- jekyll-mentions
